### ISSUE TITLE
Proposed fix for build failure on SageMath >= 10.2 / Flint 3: _fmpq_poly_interpolate_fmpq_vec removed

### ISSUE THREAD

**Issue by carlok** [mkauers/ore_algebra#155]
Build failure on SageMath >= 10.2 / Flint 3: `_fmpq_poly_interpolate_fmpq_vec` removed

## Summary

Installing `ore_algebra` from source fails to compile on any SageMath >= 10.2 that ships
with Flint 3, because `dac_sum_c.pyx` references `_fmpq_poly_interpolate_fmpq_vec`, a
private Flint 2 function that was **removed in Flint 3** and replaced by
`_fmpq_poly_interpolate_fmpz_vec`.

## Environment

| Component   | Version              |
|-------------|----------------------|
| OS          | macOS 15 (arm64)     |
| SageMath    | 10.7                 |
| Python      | 3.12                 |
| Flint       | **3.3.1**            |
| ore_algebra | commit `2904d75` (current `master`) |
| Install     | `pip install --no-build-isolation git+https://github.com/mkauers/ore_algebra.git` |

## Steps to reproduce

```bash
mamba create -n sage -c conda-forge sage python=3.12 -y
mamba run -n sage bash -c \
  "PIP_REQUIRE_VIRTUALENV=0 sage -pip install --no-build-isolation \
   git+https://github.com/mkauers/ore_algebra.git"
```

## Error output (abridged)

```
building 'ore_algebra.analytic.dac_sum_c' extension
...
src/ore_algebra/analytic/dac_sum_c.c:21879:12: error: call to undeclared function
  '_fmpq_poly_interpolate_fmpq_vec'; ISO C99 does not support implicit function declarations

note: did you mean '_fmpq_poly_interpolate_fmpz_vec'?

error: command '.../clang' failed with exit code 1
ERROR: Failed building wheel for ore_algebra
```

## Root cause

`dac_sum_c.pyx` (line 28-29) declares:

```cython
cdef extern from "flint_wrap.h":
    int _fmpq_poly_interpolate_fmpq_vec(fmpz * poly, fmpz_t den,
                                        const fmpq * xs, const fmpq * ys, slong n)
```

In **Flint 3**, this function was removed. The replacement is:

```c
void _fmpq_poly_interpolate_fmpz_vec(fmpz * poly, fmpz_t den,
                                     const fmpz * xs, const fmpz * ys, slong n);
```

The x-points in `pitvdm_stdpts()` are the integers `0, 1, -1, 2, -2, ...`
(stored as `fmpq` with denominator 1), and the y-values are unit vectors (all 0s except
a single 1). Both are already integers, so the replacement is semantically exact.

## Proposed fix

**File:** `src/ore_algebra/analytic/dac_sum_c.pyx`

```diff
 cdef extern from "flint_wrap.h":
-    int _fmpq_poly_interpolate_fmpq_vec(fmpz * poly, fmpz_t den,
-                                        const fmpq * xs, const fmpq * ys, slong n)
+    void _fmpq_poly_interpolate_fmpz_vec(fmpz * poly, fmpz_t den,
+                                         const fmpz * xs, const fmpz * ys, slong n)
```

```diff
-    cdef fmpq *points = _fmpq_vec_init(2*n-1)
-    cdef fmpq *values = _fmpq_vec_init(2*n-1)
+    cdef fmpz *ipoints = _fmpz_vec_init(2*n-1)
+    cdef fmpz *ivalues = _fmpz_vec_init(2*n-1)
     cdef fmpz *rowden = _fmpz_vec_init(n)
-    fmpq_zero(points)
+    fmpz_zero(ipoints)
     for i in range(1, n):
-        fmpq_set_si(points + 2*i - 1,  i, 1)
-        fmpq_set_si(points + 2*i,     -i, 1)
+        fmpz_set_si(ipoints + 2*i - 1,  i)
+        fmpz_set_si(ipoints + 2*i,     -i)
     for i in range(n):
         j = 0 if i == 0 else 2*i - 1
-        fmpq_one(values + j)
-        _fmpq_poly_interpolate_fmpq_vec(fmpz_mat_entry(matnum, i, 0),
-                                        rowden + i, points, values, 2*n-1)
-        fmpq_zero(values + j)
+        fmpz_one(ivalues + j)
+        _fmpq_poly_interpolate_fmpz_vec(fmpz_mat_entry(matnum, i, 0),
+                                        rowden + i, ipoints, ivalues, 2*n-1)
+        fmpz_zero(ivalues + j)
     _fmpz_vec_lcm(matden, rowden, n)
     ...
     _fmpz_vec_clear(rowden, n)
-    _fmpq_vec_clear(values, 2*n-1)
-    _fmpq_vec_clear(points, 2*n-1)
+    _fmpz_vec_clear(ivalues, 2*n-1)
+    _fmpz_vec_clear(ipoints, 2*n-1)
```

## Verification

```
Successfully built ore_algebra
Successfully installed ore_algebra-0.5
```

```bash
sage -c "from ore_algebra import OreAlgebra; print('ore_algebra OK')"
# -> ore_algebra OK
```

## Notes

- This is the **only** use of `_fmpq_poly_interpolate_fmpq_vec` in the codebase.
- Sage >= 10.2 always ships Flint 3, so a simple replacement suffices over a version guard.

**Comment by mezzarobba** [comment]
LLM slop? `_fmpq_poly_interpolate_fmpq_vec` was *added* in Flint 3.4.

**Comment by carlok** [comment]
Hi @mezzarobba, thanks for the correction.

You are right: `_fmpq_poly_interpolate_fmpq_vec` is present in Flint 3.4.  
My initial report mixed this up because the failing environment was Sage 10.7 from conda-forge on macOS arm64, which resolves to Flint 3.3.1 and fails to compile `ore_algebra` master at:

```text
error: call to undeclared function '_fmpq_poly_interpolate_fmpq_vec'
note: did you mean '_fmpq_poly_interpolate_fmpz_vec'?
```

What I verified locally:

- **conda Sage 10.7 (Flint 3.3.1):** fails on `_fmpq_poly_interpolate_fmpq_vec` unless patched.
- **patched local `dac_sum_c.pyx`:** builds and imports fine (`ore_algebra OK`) in that same environment.
- **Sage 10.8 packaging variants I tested:** did not immediately provide a clean unpatched build path on this machine due to separate packaging/Cython header issues.

So the practical blocker seems to be environment/toolchain alignment (Flint 3.3 vs 3.4), not the mathematical logic in the patch itself.

If useful, I can open a follow-up with:

1. exact `conda list` / `sage -v` / `flint` versions,  
2. full compile logs for both failing and working (patched) cases,  
3. a minimal environment matrix showing where master builds unpatched.

Thank you for your work.

**Comment by mezzarobba** [comment]
Fixed by #158.
